### ISSUE TITLE
"Getting release from indexer failed" in Radarr/Sonarr via Prowlarr

### ISSUE THREAD

**Issue by jasonleexp** [mgdigital/rarbg-selfhosted#4] opened 2023-06-11 20:44 UTC
Hey, I came here after seeing your post on /r/selfhosted.

I'm getting the error "Getting release from indexer failed" when adding a title from either Radarr or Sonarr.  

For context, I did the setup exactly as you described in your README with Prowlarr and was able to successfully test it in the Prowlarr UI.  I can even search for titles in the Radarr or Sonarr UI, but when I actually click to add to the download client, it fails with the above error message.

Any thoughts?

From the Events tab in Radarr:

`3:23pm | Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware | An unhandled exception has occurred while executing the request.: Getting release from indexer failed |`

and:

`HTTP Error - Res: [GET] ...[redacted for length]... 414.RequestUriTooLong (0 bytes)`

There's nothing in the logs for the docker container, other than the 3 initial log messages saying it's listening on port 3333

**Comment by mgdigital** [comment] 2023-06-11 20:50
Hi, I haven't seen that before, could you let me know the hash of what you're trying to add and I'll see if I can reproduce the issue? It looks like the magnet link may be too long so removing some of the trackers from your trackers.txt file may help as they all get appended...

**Comment by jasonleexp** [comment] 2023-06-11 22:43
Actually, I think there might be an issue with my setup.  I actually just pointed my Radarr instance to my RARBG self-hosted instance, directly, in order to bypass Prowlarr.  That was successful.  I was able to add the same title that I wasn't able to before.  

Hmm, I might have to do some more troubleshooting on my end... is your setup also Radarr / Sonarr --> Prowlarr --> RARBG Selfhosted?  I'm wondering if there's something I'm missing.  

One thing I just thought of is that I am using [privoxy for my Prowlarr instance](https://github.com/binhex/arch-qbittorrentvpn), but I don't think I'm pointing this specific indexer to use it?  I'm also not using my reverse proxy in my Radarr/Sonarr/Prowlarr instances, so I don't think it's that either.

**Comment by jasonleexp** [comment] 2023-06-12 13:53
@mgdigital Can you help verify if my settings are correct?  Anything I'm missing?

Prowlarr:
<img width="383" alt="prowlarr" src="https://github.com/mgdigital/rarbg-selfhosted/assets/135553398/9fe2a0ee-87c8-4bd6-992a-532ab9cde7c4">

Radarr:
<img width="328" alt="Radarr" src="https://github.com/mgdigital/rarbg-selfhosted/assets/135553398/50ce65fb-a811-4697-aa75-f13db806bf8f">

Sonarr:
<img width="540" alt="sonarr" src="https://github.com/mgdigital/rarbg-selfhosted/assets/135553398/a1932dcd-4385-47f4-bd1c-ec252b3246e8">

**Comment by mgdigital** [comment] 2023-06-12 18:02
Hi, I don't know much about the specifics of your config but I can make some suggestions:

- In Prowlarr, I think you should be using the RARBG container name instead of that IP address
- Any request under the `/torznab` path will be handled so just `http://rarbg-selfhosted:3333/torznab` should work with no API path necessary
- Make sure you're not proxying this indexer through Privoxy, I don't think that will work
- Could you pull in the latest updates from this repo from the `main` branch and run `docker-compose up -d --build` as I've fixed some bugs today
- I've created this issue as syncing the indexer from Prowlarr to Sonarr isn't working for me but your screenshots suggest it works for you... https://github.com/mgdigital/rarbg-selfhosted/issues/6

Screenshot of my working Prowlarr config:

<img width="716" alt="image" src="https://github.com/mgdigital/rarbg-selfhosted/assets/442933/8401e58e-4162-4e05-b7d3-b2a85083db53">

**Comment by jasonleexp** [comment] 2023-06-12 21:55
Ok, I've followed your instructions exactly:

* Pulled down the latest updates from `main` and rebuilt the container
* Confirmed that Prowlarr, Radarr, Sonarr, and Rarbg selfhosted are all on the same Docker network (if it matters, they're all on the `bridge` network, as I'm running Docker on a Synology NAS)
* Copied your exact Prowlarr settings, as shown in your screenshot above

I'm unable to add the indexer, it fails when I hit Test:

![image](https://github.com/mgdigital/rarbg-selfhosted/assets/135553398/def2fba8-7781-4086-bfbc-0f17cf1484a0)

**Comment by mgdigital** [comment] 2023-06-12 22:22
Hi, I deliberately didn't give exact instructions as I've no idea how your home network is configured :)

The error here indicates Prowlarr is unable to resolve the hostname you've input. I'm closing this issue as I can't provide general Docker networking or Synology NAS support - I'd suggest checking out some tutorials and once you've got the 2 containers talking to each other I expect `rarbg-selfhosted` will work fine with a similar config to what I've provided above.

**Closed by mgdigital** 2023-06-12 22:22 UTC
